### ISSUE TITLE
Question about x-pack

### ISSUE THREAD

**Issue by okcjason** [teamsoo/elasticsearch-ambari#1]
Does this project support the x-pack functionality within ElasticSearch?

**Comment by teamsoo** [comment]
Hi @okcjason, according to [ESS Doc#installing-xpack](https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#installing-xpack)

> You must install Elasticsearch and Kibana before you install X-Pack. If you plan to use the X-Pack features in Logstash, you must also install Logstash before you install X-Pack.

I believe you can install X-Pack later after you successfully deploy ESS on Ambari using this project. More information can be found in the above doc link.
